services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile-dev
    container_name: cargas_academicas_app
    depends_on:
      - db
    ports:
      - 8000:8000
    volumes:
      - ./app/cargas_academicas:/app
      - ./pruebas_aceptacion:/pruebas_aceptacion

    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      DB_USER_ADMIN: ${DB_USER_ADMIN}

      DB_HOST: ${DB_HOST}
      DEBUG: ${DEBUG}
      SECRET_KEY: ${SECRET_KEY}

  db:
    image: mariadb
    container_name: cargas_academicas_db
    # restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - db:/var/lib/mysql
    ports:
      - 127.0.0.1:3310:3306

  chrome:
    image: selenium/node-chrome:4.2.0-20220527
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS = 100

  edge:
    image: selenium/node-edge:4.2.0-20220527
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  firefox:
    image: selenium/node-firefox:4.2.0-20220527
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  selenium-hub:
    image: selenium/hub:4.2.0-20220527
    container_name: selenium-hub
    ports:
      # - "192.168.56.100:4442:4442"
      # - "192.168.56.100:4443:4443"
      # - "192.168.56.100:4444:4444"
      - 4444:4444

volumes:
  db:
