# Generated by Django 5.1 on 2025-02-11 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('clave', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Clave')),
                ('nombre', models.CharField(max_length=250, verbose_name='Nombre')),
                ('creditos', models.SmallIntegerField()),
            ],
        ),
    ]
