# Generated by Django 5.1 on 2025-02-13 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='descripcion',
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name='Descripción'),
        ),
    ]
