# Generated by Django 5.1 on 2025-02-13 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0002_materia_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='semestre',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
