# Generated by Django 5.1 on 2025-02-13 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0003_materia_semestre'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramaAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, verbose_name='Nombre')),
                ('abreviacion', models.CharField(
                    max_length=5, verbose_name='Abreviación')),
            ],
        ),
        migrations.AddField(
            model_name='materia',
            name='programa_academico',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    to='materias.programaacademico', verbose_name='Programa académico'),
            preserve_default=False,
        ),
    ]
