# Generated by Django 5.1 on 2025-02-13 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0005_unidadacademica'),
    ]

    operations = [
        migrations.AddField(
            model_name='programaacademico',
            name='unidad_academica',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    to='materias.unidadacademica', verbose_name='Unidad académica'),
            preserve_default=False,
        ),
    ]
