# Generated by Django 5.1 on 2025-03-18 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0006_programaacademico_unidad_academica'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadacademica',
            name='abreviacion',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Abreviación'),
        ),
    ]
